name: Docker FireCrawl Push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPO_NAME: nuersir # 注意使用全小写
  PROJECT_NAME: firecrawl-service

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ${{ env.PROJECT_NAME }} image
      uses: docker/build-push-action@v3
      with:
        context: ./apps/playwright-service
        file: ./apps/playwright-service/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ env.REPO_NAME }}/${{ env.PROJECT_NAME }}:latest
